[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Buy"
authors = [{name = "SirShanova", email = "steven.schiavone@gmail.com"}]
dynamic = ["version", "description"]
